# Jekyll YAML Configuration
# https://jekyllrb.com
#
# This configuration can readable using Liquid.
name: noteswiper
title: noteswiper

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

disable_disk_cache: false

url: https://noteswiper.github.io
sitemap: true

future: true

author:
  twitter: https://twitter.com/alphabetloreFAZ
  youtube: https://www.youtube.com/@noteswiper

include: 
  - _core
  - core
  - _apis
  - _api
  - apis
  - api
  - _resources
  - res
  - _pages

exclude: []
keep_files:
  - ".git"

encoding: utf-8

timezone: Asia/Tokyo


youtube_handle: "https://www.youtube.com/"
twitteruser: "https://twitter.com"
githubuser: "https://github.com"
twitchuser: "https://twitch.tv"
deviantartuser: "https://deviantart.com"

shortBlox:
  devforum: "devforum.link/"
  library: "rblx.media/"
  group: "rblx.social/"
  catalog: "rblx.clothing/"
  user:
    usrId: "rblx.name/"
    usrName: "user.rblx.name/"
  game: "rblx.games/"

source: .
destination: ./_site
collections_dir: .

description: something

noteswiper:
  author: noteswiper
  youtube:
    main:
      name: 'Note Swiper'
      handle: noteswiper
    sub:
      name: 'alphabetFAZ'
      handle: alphabetFAZ
  twitter:
    id: alphabetloreFAZ
  github:
    name: NoteSwiper

feed:
  posts_limit: 128
  tags: true

lsi: true

sass:
  style: compressed
  sass_dir: _sass

safe: false
plugins: 
   - jekyll-avatar
  # - jekyll-feed 
  # - Liquid-md5
  # - Liquid_reading_time
  # - jekyll-analytics
   - jekyll-archives
  # - jekyll-assets
   - jekyll-gist
   - jekyll-github-metadata
  # - jekyll-google_search_console_verification_file
  # - jekyll-i18n_tags
  # - jekyll-imgix
  # - jekyll-language-plugin
  # - jekyll-loading-lazy
  # - jekyll-localization
  # - jekyll-manager
   - jekyll-mentions
  # - jekyll-minibundle
  # - jekyll-minifier
  # - jekyll-pwa-workbox
   - jekyll-redirect-from
  # - jekyll-rendering
  # - jekyll-responsive_image
   - jekyll-sass-converter
   - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-webp
  # - jekyll-tagging
  # - jekyll-tagging-related_posts
  # - jekyll-target-blank
   - jekyll-toc
  # - jekyll-youtube
  # - jekyll_image_encode
   - jemoji
  # - searchyll
  # - jekyll-tsc

typescript:
  temp_dir: .typescript
  extensions: ['.ts', '.tsx']
  copy_ext: []
  command: ['tsc']
  cache: true

profile: true

jekyll-minifier:
  exclude: 'atom.xml'

defaults: 
  -
    scope:
          path: ""
          type: "posts"
    values:
      image: "/assets/img/pr0cdures_preview.png"
  -
    scope:
          path: ""
          type: "trInfo"
    values:
          test: "test"
  - scope:
          path: ""
    values:
          sitemap: true
  - scope:
      path: ".jpg"
    values:
      type: image
      type_ext: JPEG
  - scope:
      path: ".png"
    values:
      type: image
      type_ext: PNG
  - scope:
      path: ".gif"
    values:
      type: image
      type_ext: GIF
  - scope:
      path: ".jpeg"
    values:
      type: image
      type_ext: JPEG
  - scope:
      path: "/assets/img"
    values:
      type: asset_image
      type_ext: Images

webrick:
  headers:
    test: "false"

assets:
  source_maps: true
  destination: "/assets/cached"
  compression: true
  gzip: false
  defaults:
    integrity:
      {css,img,js}: false
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  precompile: []

source_lang: en

page_excerpts: true

elasticsearch:
  url: "https://noteswiper.github.io"

tag_page_layout: tag_page
tag_page_dir: tags

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 320
    - width: 480
    - width: 800

webp:
  enabled: false
  quality: 75
  img_dir: ["/img"]
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  gifs: [".gif", ".apng"]
  regenerate: false

imgix:
  source: assets.imgix.net

jekyll_analytics:
  GoogleAnalytics:
    id:
    anonymizeIp: false

jekyll-mentions:
  base_url: https://twitter.com

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section_nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

markdown: kramdown
highlighter: rouge



titles_from_headings:
  enabled: true
  strip_title: false
  collections: false

collections:
  posts:
    output: true
  pages:
    output: true
  trInfo:
    sort_by: sortId
    output: true

limit_posts: 0

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input: GFM
  hard_wrap: false
  gfm_emojis: true
  auto_id_prefix: "id" 
  auto_id_stripping: true
  auto_ids: true
  entity_output: as_char
  footnote_backlink: "&#8617;"
  footnote_backlink_inline: "false"
  footnote_nr: 1
  footnote_prefix: "fp"
  header_offset: 0
  html_to_native: false
  latex_headers: section,subsection,subsubsection,paragraph,subparagraph,subparagraph
  line_width: 72
  math_engine: mathjax
  parse_block_html: false
  parse_span_html: true
  remove_block_html_tags: true
  remove_line_breaks_for_cjk: false
  remove_span_html_tags: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  template: none
  transliterated_header_ids: true

permalink: /:categories/:year/:month/:day/:title:output_ext

pagination:
  enabled: true
  per_page: 16
  sort_reverse: true
  limit: 0
  sort_field: 'date'
  permalink: '/page/:num/'
  title: ':title'
  trail:
    before: 3
    after: 3

languages: ['ja','en']
default_lang: 'en'
exclude_from_localization: ['javascript','images','css']
parallel_localization: false
excerpt_separator: \n\n
language_data: data.lang.%%
language_includes_dir: _i18n
show_dir_listing: true
plugins_dir: _plugins
data_dir: _data

show_drafts: true
