# Gemfile
# marked `#gh` has listed on "https://pages.github.com/versions/"
source "https://rubygems.org"
gem "ruby"
gem "sprockets"
gem "uglifier"
gem "jekyll"
gem "html-pipeline"

group :jekyll_plugins do
    gem "classifier-reborn"
    gem "jekyll-avatar"
    gem "jekyll-coffeescript"
    gem "jekyll-commonmark-ghpages"
    gem "jekyll-default-layout"
    gem "jekyll-gist"
    gem "jekyll-github-metadata"
    gem "jekyll-include-cache"
    gem "jekyll-mentions"
    gem "jekyll-optional-front-matter"
    gem "jekyll-paginate"
    gem "jekyll-readme-index"
    gem "jekyll-redirect-from"
    gem "jekyll-remote-theme"
    gem "jekyll-sass-converter"
    gem "jekyll-seo-tag"
    gem "jekyll-titles-from-headings"
    gem "jekyll-relative-links"
    gem "jekyll-localization"
    gem "jekyll-tagging"
    gem "jekyll_image_encode"
    gem "jemoji"
end

gem "kramdown"
gem "liquid"
gem "nokogiri"
gem "rouge"

gem "safe_yaml"
gem "sass"