source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
    gem "classifier-reborn"
    gem "jekyll-analytics"
    gem "jekyll-archives"
    gem "jekyll-assets"
    gem "jekyll-avatar"
    gem "jekyll-coffeescript"
    gem "jekyll-feed"
    gem "jekyll-gist"
    gem "jekyll-github-metadata"
    gem "jekyll-google_search_console_verification_file"
    gem "jekyll-i18n_tags"
    gem "jekyll-imgix"
    gem "jekyll-language-plugin"
    gem "jekyll-loading-lazy"
    gem "jekyll-localization"
    gem "jekyll-manager"
    gem "jekyll-mentions"
    gem "jekyll-minibundle"
    gem "jekyll-minifier"
    gem "jekyll-pwa-workbox"
    gem "jekyll-redirect-from"
    gem "jekyll-rendering"
    gem "jekyll-responsive_image"
    gem "jekyll-sass-converter"
    gem "jekyll-seo-tag"
    gem "jekyll-sitemap"
    gem "jekyll-tagging"
    gem "jekyll-tagging-related_posts"
    gem "jekyll-target-blank"
    gem "jekyll-toc"
    gem "jekyll-tsc"
    gem "jekyll-webp"
    gem "jekyll-youtube"
    gem "jekyll_image_encode"
    gem "jemoji"
    gem "kramdown-syntax-coderay"
    gem "searchyll"
end